version: '3.5'

services:
  network-proxy:
    container_name: network-proxy-dev
    image: liyaodev/network-proxy-dev:v1.0.0
    # 本地构建
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7777:7777
    volumes:
      - .:/www/server:delegated
      - ${NETWORK_PROXY_ROOT_DIR:-.}/volumes/vscode-extensions:/www/.vscode-server:delegated
    depends_on:
      - shadowsocks
  
  shadowsocks:
    container_name: network-proxy-shadowsocks
    image: shadowsocks/shadowsocks-libev:latest
    ports:
      - "8388:8388"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=${PASSWORD:-shadowsocks}

networks:
  default:
    name: network_proxy_dev
